spring.application.name=com
spring.datasource.url=jdbc:postgresql://ep-rapid-dew-ay0mdhif-pooler.c-5.us-east-2.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_cjOF2WkYAy7G
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080

# JWT Configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-token.expiration=3600000
jwt.refresh-token.expiration=86400000
